{{- if .Values.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "patchmon.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "patchmon.labels" . | nindent 4 }}
  {{- with .Values.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  CORS_ORIGIN: {{ .Values.backend.env.corsOrigin | quote }}
  SERVER_HOST: {{ .Values.backend.env.serverHost | quote }}
  SERVER_PORT: {{ .Values.backend.env.serverPort | quote }}
  SERVER_PROTOCOL: {{ .Values.backend.env.serverProtocol | quote }}
{{- end }}
